cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    arvin:
      email: arvin@mail.com
      failed_login_attempts: 0
      logged_in: true
      name: Arvin
      password: $2b$12$q/eQwYkVK1eDtlpqRrluy.Re.tiwr9VZ7XeL6rPWgP9hBhEa00pwe
    arvin31:
      email: arvinaliasrv@gmail.com
      failed_login_attempts: 1
      logged_in: false
      name: Arvin
      password: $2b$12$.Krd/liHumYwS7sAtelqRec8qqkHnOIvsDH12RHNlrqeclGuPJPpe
      pp: PWck67mxOtNe1lfa
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: John Smith
      password: $2b$12$iWlVOac3uujRvTrXDi6wructXftKmo/GyQd6SMu5FmyX306kH.yFO
    new:
      email: newuser1@gmail.com
      logged_in: false
      name: newuser
      password: $2b$12$ND8dslFtsRpf60z6zosO2.ZYF34.9sHsKEwNZqATTq6UZh5CYogBm
    newuser:
      email: newuser@mail.com
      logged_in: false
      name: newuser
      password: $2b$12$CrwEB1AJU61cVThUr4JLxOUP/V.IJUmOZuENUBWBLgBHRtYUuBcN.
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$uNaTgvGPG9rMbzOJHYaPQePw0DUfp1qHBrSq6l4O304qani6pKFpm
    sudha:
      email: sudha@mail.com
      logged_in: false
      name: Sudha
      password: $2b$12$2vRDsTCaD5jmObnxTO4c9eufY1hnzAT0mftNJFLoTicpHb/t7ncla
pre-authorized:
  emails:
  - melsby@gmail.com
